### ISSUE TITLE
promoting

### ISSUE THREAD

**Issue by a-eniou-pvotal** [Luckey-Elijah/gator#13]
your tool is cool
you could promote it in flutter weekly newsletters like Flutter tap
https://fluttertap.com/

**Comment by Luckey-Elijah** [comment]
Thanks for the kind words! I will take a look and see if I could promote it there

**Comment by Luckey-Elijah** [comment]
I'll be closing this issue since it has been seen in https://fluttertap.com/issue-125/. 
Thanks!
